### ISSUE TITLE
Horizon fails to start for public, complains history-archive-urls unset

### ISSUE THREAD

**Issue by bitmodeler** [stellar/packages#115]
See this for the standalone error:

[https://github.com/stellar/docker-stellar-core-horizon/issues/162](https://github.com/stellar/docker-stellar-core-horizon/issues/162)

Where do I start?

I'm using stellar-quickstart 12.4.0. In the environment variables file for horizon, I have:

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

1) First off, an example I found elsewhere on the web uses bracketed strings for specifying multiple servers for HISTORY_ARCHIVE_URLS (["server1", "server2"...]); the example suggested in the post cited above uses a single string with embedded commas for multiple servers. So which is it? [for the moment I will use the single server you suggested as a single string: "https://history.stellar.org/prd/core-live/core_live_001"...]

2) I am getting this from my app when it tries to use the horizon server:
"type": "https://stellar.org/horizon-errors/still_ingesting",
  "title": "Still Ingesting",
  "status": 503,
  "detail": "Data cannot be presented because it's still being ingested. Please wait for several minutes before trying your request again."

Well I wait minutes, hours; still get the same error.

So I try putting a LOG_LEVEL="debug" in the environment file for the horizon service (/etc/default/stellar-horizon) -some posts suggested that might work; but the log remains empty, nothing indicating that the service is doing anything.

Do I need to set ingest=true for horizon's history to work for the public network? (it is set that way, as stellar-quickstart had it...) Do I set HISTORY_ARCHIVE_URLS to a localhost URL associated with my stellar-core??

How can I tell from logs or curl commands if it's actually ingesting history? (I lost my history when a debian repo update of core got installed and am now trying a new catchup of core...)

I also saw a command online: horizon db backfill
But the latest version does not have it??

**Comment by bartekn** [comment]
@bitmodeler this should be a comma separated list of values, like `history1,history2`, if there's a single one: no commas. See: https://github.com/stellar/go/releases/tag/horizon-v1.0.0
> * A new environment variable (or command line flag) needs to be set so that Horizon can ingest state from the history archives:
>   * `HISTORY_ARCHIVE_URLS="archive1,archive2,archive3"` (if you don't have your own pubnet history archive, you can use one of SDF's archives, for example `https://history.stellar.org/prd/core-live/core_live_001`)

**Comment by aliuchuang** [comment]
How to solve this problem 
{
"type": "https://stellar.org/horizon-errors/still_ingesting",
"title": "Still Ingesting",
"status": 503,
"detail": "Data cannot be presented because it's still being ingested. Please wait for several minutes before trying your request again."
}
