### ISSUE TITLE
Horizon installation process is not terminated if migrations fail

### ISSUE THREAD

**Issue by bartekn** [stellar/packages#147]
### What did you do?

I noticed that Horizon installation process is not terminated if `db migrate up` command fails.

### What did you expect to see?

If `db migrate up` fails (Horizon returns `1` exit code) I'd expect the process to stop and revert the changes to the previously installed version.

### What did you see instead?

New version of Horizon started without applied migrations.

**Comment by brahman81** [comment]
This is expected behaviour if the postinst script exits with non zero code. We might be able to work around this but it's generally safer to fail with unexpected results. Update to follow.

**Comment by jacekn** [comment]
This was addressed in https://github.com/stellar/packages/pull/169
