### ISSUE TITLE
core upgrade "fails" attempting to override core config file

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/packages#148]
### What did you do?

    apt-get install stellar-core=17.2.0-615.e47d483.focal
    # make modifications to the config file and mark the file immutable
    chattr +i /etc/stellar/stellar-core.cfg
    apt-get install stellar-core=17.3.0-647.0b4c12a.focal

### What did you expect to see?

no error message

### What did you see instead?

    “chown: changing ownership of '/etc/stellar/stellar-core.cfg': Operation not permitted”

I would not expect to see this error - the config file should not be overridden or modified by apt

**Comment by xiv** [comment]
This has been resolved closing this ticket. 

Immutable bit has been removed.
