### ISSUE TITLE
stellar-quickstart impish version

### ISSUE THREAD

**Issue by EminBudak** [stellar/packages#155]
Ubuntu 21, I cannot install **sudo apt-get update && sudo apt-get install stellar-quickstart** because there is no impish version. 

I changed stellar package to xenial (in /etc/apt/sources.list.d/SDF.list) but when I tried to install it gives an error because there is a higher version on libc++1 installed on the system.

**The following packages have unmet dependencies:
 stellar-core : Depends: libc++1-8 but it is not installable
                Depends: libc++abi1-8 but it is not installable**

**Comment by jacekn** [comment]
Apologies for late reply. We only support Ubuntu LTS releases. Currently those are ubuntu 18.04 (bionic) and Ubuntu 20.04 (focal).
If you can move to one of the supported releases package installation should work on them.

However if you can't move you may be able to use official docker images to run out software on non-supported systems. If you'd like to explore this option there is documentation [here](https://developers.stellar.org/docs/run-core-node/installation/#production-environments)
