### ISSUE TITLE
stellar-horizon version  returns incorrect info'

### ISSUE THREAD

**Issue by glowkeeper** [stellar/packages#16]
Not really an issue, more a 'nice to know' :) After installing `stellar-quickstart` from this repository, `stellar-horizon version` returns incorrect info':  

    $ stellar-horizon version  
    snapshot-snapshots

Whereas...

    $ dpkg -s stellar-horizon
    Package: stellar-horizon
    Status: install ok installed
    Priority: optional
    Section: web
    Installed-Size: 11800
    Maintainer: Package Maintainer <packages@stellar.org>
    Architecture: amd64
    Version: 0.12.3-17

**Comment by brahman81** [comment]
@glowkeeper Thanks for the report, we have just pushed out an update to the stable and unstable repositories which fixes this issue. The version is now correctly reported by stellar-horizon.

```
$ stellar-horizon version
0.13.2-1968a7e962790c66c72701846a108d6d96288a3b
```
Apologies for this taking so long to rectify.
