### ISSUE TITLE
can't install via packages on ubuntu 20.04

### ISSUE THREAD

**Issue by visualbasic6** [stellar/packages#184]
```
Err:8 https://apt.stellar.org kinetic Release
  404  Not Found [IP: 172.64.145.253 443]
```
any help? not using docker 🙄

**Comment by jacekn** [comment]
It's hard to tell for sure without looking at your apt source config but you may have misconfigured the release name.
Ubuntu 20.04 codename is "focal" but I can see "kinetic" in the error message (kinetic is Ubuntu 22.10).

I've just tested with the following config on Ubuntu 20.04:
```
deb https://apt.stellar.org focal stable
```
and everything seems to work as expected.

I'll close this issue but if you think there is a problem with the 20.04 repo please let us know.
