### ISSUE TITLE
Cannot pull stellar-quickstart

### ISSUE THREAD

**Issue by istrau2** [stellar/packages#3]
On a newly instantiated AWS AMI AWS AMI Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-965e6bf3

1. First I ran:
```
sudo apt-get update
```
That ran fine.

2. Then I ran this:

```
ubuntu@ip-172-31-17-76:~$ sudo apt-get install stellar-quickstart
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package stellar-quickstart
```

**Comment by lhfly5201314** [comment]
Hi,friend!How do you fix the problem?
I just met the same issue!!
Please help!Thanks!
