### ISSUE TITLE
Where is Horizon setting

### ISSUE THREAD

**Issue by Cheny-chen** [stellar/packages#85]
Where can I find horizon setting?

If I want to change horizon port or other setting, how to do?

**Comment by mgreville** [comment]
Hi Chenny-chen,

Horizon is configured via command options or environment variables and executing `stellar-horizon --help` will list all them all for you. Have a look at the [Administration Guide](https://github.com/stellar/go/blob/master/services/horizon/internal/docs/admin.md) for further detail.

 For the specific case of changing the default port you can either use `--port=9999` or set an environment varaible to `PORT=9999`.

As the documentation says, using command switches is unwieldy so stick with an environment values file, such as `/etc/default/stellar-horizon` which is sourced by the `stellar-horizon.service` systemd startup script

**Comment by brahman81** [comment]
If using the packages to install Horizon, you will need to modify `/etc/default/stellar-horizon` as detailed:

https://github.com/stellar/packages/blob/master/docs/installing-individual-packages.md#installing-individual-packages
